name: frontend_nyatet_app_flutter
description: "Mobile Nyatet App"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  intl: ^0.20.0
  bloc: ^8.1.4
  dartz: ^0.10.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
